### ISSUE TITLE
not resolved: www.youtube.com

### ISSUE THREAD

**Issue by Freemorger** [hufrea/byedpi#92]
I run byedpi: 
`./ciadpi-x86_64 -s2 -d2`
and when i try to go to any site with proxy on, it gaves me an error in terminal, like:

> not resolved: www.youtube.com

**Comment by zimbabwe303** [comment]
Try setting your system DNS to `1.1.1.1` in the network adapter properties. As far as I understand byedpi does DNS resolving using the system mechanism (in contrast to SpoofDPI which even has some kind of internal DNS-over-HTTPS, but unfortunately otherwise has much less features).
![Screenshot](https://github.com/user-attachments/assets/0318e7d9-6f8b-47f1-ab4c-49d8871aea09)

**Comment by Freemorger** [comment]
> Try setting your system DNS to `1.1.1.1` in the network adapter properties. As far as I understand byedpi does DNS resolving using the system mechanism (in contrast to SpoofDPI which even has some kind of internal DNS-over-HTTPS, but unfortunately otherwise has much less features).
> ![Screenshot](https://github.com/user-attachments/assets/0318e7d9-6f8b-47f1-ab4c-49d8871aea09)
> 

That worked. Thx. Closing.
